// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RX.Gateway.Repository.EF;

namespace RX.Gateway.Repository.EF.Migrations
{
    [DbContext(typeof(RxGatewayDbContext))]
    partial class RxGatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RX.Gateway.Model.Core.Acquirier", b =>
                {
                    b.Property<Guid>("ObjectID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ObjectID");

                    b.ToTable("Acquiriers");
                });

            modelBuilder.Entity("RX.Gateway.Model.Core.AntiFraud", b =>
                {
                    b.Property<Guid>("ObjectID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ObjectID");

                    b.ToTable("AntiFrauds");
                });

            modelBuilder.Entity("RX.Gateway.Model.Core.Shopkeeper", b =>
                {
                    b.Property<Guid>("ObjectID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid?>("StoreObjectID");

                    b.HasKey("ObjectID");

                    b.HasIndex("StoreObjectID");

                    b.ToTable("Shopkeepers");
                });

            modelBuilder.Entity("RX.Gateway.Model.Core.ShopkeeperAcquirierCredcardBrand", b =>
                {
                    b.Property<Guid>("ShopkeeperID");

                    b.Property<Guid>("AcquirierID");

                    b.Property<int>("CreditCardBrand");

                    b.HasKey("ShopkeeperID", "AcquirierID", "CreditCardBrand");

                    b.HasIndex("AcquirierID");

                    b.ToTable("ShopkeeperAcquirierCredcardBrand");
                });

            modelBuilder.Entity("RX.Gateway.Model.Core.Store", b =>
                {
                    b.Property<Guid>("ObjectID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ObjectID");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("RX.Gateway.Model.Core.StoreAcquirier", b =>
                {
                    b.Property<Guid>("StoreObjectID");

                    b.Property<Guid>("AcquirierObjectID");

                    b.HasKey("StoreObjectID", "AcquirierObjectID");

                    b.HasIndex("AcquirierObjectID");

                    b.ToTable("StoreAcquirier");
                });

            modelBuilder.Entity("RX.Gateway.Model.Core.StoreAntiFraud", b =>
                {
                    b.Property<Guid>("StoreObjectID");

                    b.Property<Guid>("AntiFraudObjectID");

                    b.HasKey("StoreObjectID", "AntiFraudObjectID");

                    b.HasIndex("AntiFraudObjectID");

                    b.ToTable("StoreAntiFraud");
                });

            modelBuilder.Entity("RX.Gateway.Model.Transaction.CreditCardTransactionRegistry", b =>
                {
                    b.Property<Guid>("ObjectID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AcquirierId");

                    b.Property<long>("AmountInCents");

                    b.Property<Guid>("AntiFraudId");

                    b.Property<int>("Brand");

                    b.Property<string>("CreditCardNumber")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("ExpMonth");

                    b.Property<int>("ExpYear");

                    b.Property<string>("HolderName");

                    b.Property<int>("InstallmentCount");

                    b.Property<string>("OrderNumber");

                    b.Property<Guid>("ShopkeeperId");

                    b.Property<int>("Status");

                    b.HasKey("ObjectID");

                    b.ToTable("TransactionRegistries");
                });

            modelBuilder.Entity("RX.Gateway.Model.Core.Shopkeeper", b =>
                {
                    b.HasOne("RX.Gateway.Model.Core.Store", "Store")
                        .WithMany("Shopkeepers")
                        .HasForeignKey("StoreObjectID");
                });

            modelBuilder.Entity("RX.Gateway.Model.Core.ShopkeeperAcquirierCredcardBrand", b =>
                {
                    b.HasOne("RX.Gateway.Model.Core.Acquirier", "Acquirier")
                        .WithMany()
                        .HasForeignKey("AcquirierID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RX.Gateway.Model.Core.Shopkeeper", "Shopkeeper")
                        .WithMany("AcquirierByBrand")
                        .HasForeignKey("ShopkeeperID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RX.Gateway.Model.Core.StoreAcquirier", b =>
                {
                    b.HasOne("RX.Gateway.Model.Core.Acquirier", "Acquirier")
                        .WithMany()
                        .HasForeignKey("AcquirierObjectID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RX.Gateway.Model.Core.Store", "Store")
                        .WithMany("Acquiriers")
                        .HasForeignKey("StoreObjectID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RX.Gateway.Model.Core.StoreAntiFraud", b =>
                {
                    b.HasOne("RX.Gateway.Model.Core.AntiFraud", "AntiFraud")
                        .WithMany()
                        .HasForeignKey("AntiFraudObjectID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RX.Gateway.Model.Core.Store", "Store")
                        .WithMany("AntiFrauds")
                        .HasForeignKey("StoreObjectID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
